### ISSUE TITLE
Dataset Structure

### ISSUE THREAD

**Issue by zafirshi** [jamycheung/MatchFormer#1]
Hi~ Thx for your excellent work!

I now have some problems when running the test code.It may be caused by the wrong file structure.

In fact, I'm not familiar with the structure of the two data sets of _scannet_ and _megadepth._ I don't know where to download the `megadepth_test_1500.txt` file 

https://github.com/jamycheung/MatchFormer/blob/5f40637d2dff0035e19624caf9258df5bd6ae781/config/data/megadepth_test_1500.py#L8

Could you give me some help on downloading and  organizing the dataset structure? Or modify the readme file to make the data format configuration easier?

Looking forward to your reply, and wish you have a nice day!

**Comment by Qing-WANG-KIT** [comment]
You can find it here.

https://drive.google.com/drive/folders/1SrIn9WJ1IuG08yh2nEvIsLftXHLrrIwh
