### ISSUE TITLE
about ClusterGNN.

### ISSUE THREAD

**Issue by PANFEI-CHENG** [jamycheung/MatchFormer#10]
感谢您杰出的工作！我想请问您论文中涉及到ClusterGNN: Cluster-based Coarse-to-Fine Graph Neural Network for Efficient
Feature Matching（cvpr2022）部分的实验数据是怎么获得的，据我所知，原作者并没有开源代码，您自己复现了它么？能否和我分享一下您复现的这部分工作？或者您知道哪里有相关的开源，万分感谢！我的邮箱是chengpf@hnu.edu.cn或者1915817974@qq.com

**Comment by jamycheung** [comment]
Hi, thanks for your interest in our work. 
About results of the mentioned work, we did not reproduce it but reuse the results provided in their original paper.

**Comment by PANFEI-CHENG** [comment]
Thank you for your quick reply.




---Original---
From: "Jiaming ***@***.***&gt;
Date: Wed, Sep 6, 2023 23:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jamycheung/MatchFormer] about ClusterGNN. (Issue #10)




 
Hi, thanks for your interest in our work.
 About results of the mentioned work, we did not reproduce it but reuse the results provided in their original paper.

**Comment by zhangsngood** [comment]
> 感谢您杰出的工作！我想请问您论文中涉及到ClusterGNN: Cluster-based Coarse-to-Fine Graph Neural Network for Efficient Feature Matching（cvpr2022）部分的实验数据是怎么获得的，据我所知，原作者并没有开源代码，您自己复现了它么？能否和我分享一下您复现的这部分工作？或者您知道哪里有相关的开源，万分感谢！我的邮箱是[chengpf@hnu.edu.cn](mailto:chengpf@hnu.edu.cn)或者[1915817974@qq.com](mailto:1915817974@qq.com)

你好，请问你目前有找到clusterGNN的相关代码吗
