### ISSUE TITLE
Fail to run model

### ISSUE THREAD

**Issue by felipecadar** [jamycheung/MatchFormer#2]
I want to use the matcher outside the test script, but i'm unable to build the model :/ 

the function Matchformer_SEA_lite() asks for a config in the first argument [(line)](https://github.com/jamycheung/MatchFormer/blob/5f40637d2dff0035e19624caf9258df5bd6ae781/model/backbone/match_SEA_large.py#L208)

but the [build_backbone](https://github.com/jamycheung/MatchFormer/blob/5f40637d2dff0035e19624caf9258df5bd6ae781/model/backbone/__init__.py#L7) function, does not pass any config ahead [(line)](https://github.com/jamycheung/MatchFormer/blob/5f40637d2dff0035e19624caf9258df5bd6ae781/model/backbone/__init__.py#L13)

### Code

```
config = get_cfg_defaults()

# adjust lite SEA model config:
config.MATCHFORMER.BACKBONE_TYPE = 'litesea'
config.MATCHFORMER.SCENS = 'outdoor'
config.MATCHFORMER.RESOLUTION = (8,4)

model = PL_LoFTR(config, pretrained_ckpt="./pretrained/indoor-lite-LA.ckpt", dump_dir="/tmp")
```

### Traceback

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_38/1928295852.py in <module>
      6 config.MATCHFORMER.RESOLUTION = (8,4)
      7 
----> 8 model = PL_LoFTR(config, pretrained_ckpt="./pretrained/indoor-lite-LA.ckpt", dump_dir="/tmp")

/kaggle/working/MatchFormer/model/lightning_loftr.py in __init__(self, config, pretrained_ckpt, profiler, dump_dir)
     27 
     28         # Matcher: LoFTR
---> 29         self.matcher = Matchformer(config=_config['matchformer'])
     30 
     31         # Pretrained weights

/kaggle/working/MatchFormer/model/matchformer.py in __init__(self, config)
     14         # Misc
     15         self.config = config
---> 16         self.backbone = build_backbone(config)
     17         self.coarse_matching = CoarseMatching(config['match_coarse'])
     18         self.fine_preprocess = FinePreprocess(config)

/kaggle/working/MatchFormer/model/backbone/__init__.py in build_backbone(config)
     11         return Matchformer_LA_large()
     12     elif config['backbone_type'] == 'litesea':
---> 13         return Matchformer_SEA_lite()
     14     elif config['backbone_type'] == 'largesea':
     15         return Matchformer_SEA_large()

TypeError: __init__() missing 1 required positional argument: 'config'

```

Am I doing something terrible wrong ?

**Comment by quantumalaviya** [comment]
I think the `config` argument can simply be removed from the definition of `Matchformer_SEA_lite`. However, even after that, the pretrained weights seem to be incompatible with the implementation offered here.

**Comment by Qing-WANG-KIT** [comment]
I'm very sorry, I tested it before, it works, I may need time to test it again, I've been busy with other things recently.

**Comment by Qing-WANG-KIT** [comment]
Hi, I'm busy with other things lately, I'll double check afterwards.

**Comment by Qing-WANG-KIT** [comment]
I fixed this bug, you can test it according to the updated readme.
