### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by jlinjy** [jamycheung/MatchFormer#3]
Hi! While trying to run the test in a jupyter notebook, I was able to initialise the model with 

```
pl.seed_everything(config.TRAINER.SEED)  # reproducibility
model = PL_LoFTR(config, pretrained_ckpt="../input/matchformer/MatchFormer/model/weights/outdoor-lite-SEA.ckpt", dump_dir="dump/")
# lightning data
data_module = MultiSceneDataModule(args, config)
# lightning trainer
trainer = pl.Trainer.from_argparse_args(args, logger=False, accelerator="gpu", gpus=1)
```
However, upon running
`trainer.test(model, datamodule=data_module, verbose=True)`

I am getting
```

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_33/3924240025.py in <module>
----> 1 trainer.test(model, datamodule=data_module, verbose=True)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in test(self, model, dataloaders, ckpt_path, verbose, datamodule)
    934         """
    935         self.strategy.model = model or self.lightning_module
--> 936         return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
    937 
    938     def _test_impl(

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    719                 return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    720             else:
--> 721                 return trainer_fn(*args, **kwargs)
    722         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    723         except KeyboardInterrupt as exception:

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _test_impl(self, model, dataloaders, ckpt_path, verbose, datamodule)
    981 
    982         # run test
--> 983         results = self._run(model, ckpt_path=self.ckpt_path)
    984 
    985         assert self.state.stopped

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1170         self.__setup_profiler()
   1171 
-> 1172         self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
   1173 
   1174         # check if we should delay restoring checkpoint till later

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_setup_hook(self)
   1488 
   1489         if self.datamodule is not None:
-> 1490             self.datamodule.setup(stage=fn)
   1491         self._call_callback_hooks("setup", stage=fn)
   1492         self._call_lightning_module_hook("setup", stage=fn)

/kaggle/input/matchformer/MatchFormer/model/data.py in setup(self, stage)
    114 
    115         try:
--> 116             self.world_size = dist.get_world_size()
    117             self.rank = dist.get_rank()
    118             logger.info(f"[rank:{self.rank}] world_size: {self.world_size}")

/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in get_world_size(group)
    865         return -1
    866 
--> 867     return _get_group_size(group)
    868 
    869 

/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in _get_group_size(group)
    323     """
    324     if group is GroupMember.WORLD or group is None:
--> 325         default_pg = _get_default_group()
    326         return default_pg.size()
    327     return group.size()

/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in _get_default_group()
    428     if not is_initialized():
    429         raise RuntimeError(
--> 430             "Default process group has not been initialized, "
    431             "please make sure to call init_process_group."
    432         )

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

It seems to an error related to DistributedDataParallel but I am running on only 1 gpu. 
Any help will be appreciated, thank you!

**Comment by v-v** [comment]
@jlinjy did you manage to solve it?
I'm having the same issue when trying it run (not in a notebook, same problem locally as a cli).

**Comment by cocoChen-star** [comment]
> Hi! While trying to run the test in a jupyter notebook, I was able to initialise the model with
> 
> ```
> pl.seed_everything(config.TRAINER.SEED)  # reproducibility
> model = PL_LoFTR(config, pretrained_ckpt="../input/matchformer/MatchFormer/model/weights/outdoor-lite-SEA.ckpt", dump_dir="dump/")
> # lightning data
> data_module = MultiSceneDataModule(args, config)
> # lightning trainer
> trainer = pl.Trainer.from_argparse_args(args, logger=False, accelerator="gpu", gpus=1)
> ```
> 
> However, upon running `trainer.test(model, datamodule=data_module, verbose=True)`
> 
> I am getting
> 
> ```
> 
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_33/3924240025.py in <module>
> ----> 1 trainer.test(model, datamodule=data_module, verbose=True)
> 
> /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in test(self, model, dataloaders, ckpt_path, verbose, datamodule)
>     934         """
>     935         self.strategy.model = model or self.lightning_module
> --> 936         return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
>     937 
>     938     def _test_impl(
> 
> /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
>     719                 return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
>     720             else:
> --> 721                 return trainer_fn(*args, **kwargs)
>     722         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
>     723         except KeyboardInterrupt as exception:
> 
> /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _test_impl(self, model, dataloaders, ckpt_path, verbose, datamodule)
>     981 
>     982         # run test
> --> 983         results = self._run(model, ckpt_path=self.ckpt_path)
>     984 
>     985         assert self.state.stopped
> 
> /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
>    1170         self.__setup_profiler()
>    1171 
> -> 1172         self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
>    1173 
>    1174         # check if we should delay restoring checkpoint till later
> 
> /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_setup_hook(self)
>    1488 
>    1489         if self.datamodule is not None:
> -> 1490             self.datamodule.setup(stage=fn)
>    1491         self._call_callback_hooks("setup", stage=fn)
>    1492         self._call_lightning_module_hook("setup", stage=fn)
> 
> /kaggle/input/matchformer/MatchFormer/model/data.py in setup(self, stage)
>     114 
>     115         try:
> --> 116             self.world_size = dist.get_world_size()
>     117             self.rank = dist.get_rank()
>     118             logger.info(f"[rank:{self.rank}] world_size: {self.world_size}")
> 
> /opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in get_world_size(group)
>     865         return -1
>     866 
> --> 867     return _get_group_size(group)
>     868 
>     869 
> 
> /opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in _get_group_size(group)
>     323     """
>     324     if group is GroupMember.WORLD or group is None:
> --> 325         default_pg = _get_default_group()
>     326         return default_pg.size()
>     327     return group.size()
> 
> /opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py in _get_default_group()
>     428     if not is_initialized():
>     429         raise RuntimeError(
> --> 430             "Default process group has not been initialized, "
>     431             "please make sure to call init_process_group."
>     432         )
> 
> RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
> ```
> 
> It seems to an error related to DistributedDataParallel but I am running on only 1 gpu. Any help will be appreciated, thank you!
If you want to test your dataset, where should you change the address of your dataset? Can you give me some help?
