### ISSUE TITLE
the scannet_test_1500.py test path is wrong

### ISSUE THREAD

**Issue by longzeyilang** [jamycheung/MatchFormer#5]
感谢你的工作，这个test demo根本行不通。以scannet为例，scannet_test.txt和test.npz如何的来，原来的LoFTR根本没有这些，你自己测试过了吗？

**Comment by Lisachinasd** [comment]
> 感谢你的工作，这个测试demo根本行不通。以scannet为例，scannet_test.txt和test.npz是怎么来的，原来的LoFTR根本没有这些，你自己测试过吗？

Hello, I met the same problem, can you tell me you find scannet_test. TXT and test NPZ file? Looking forward to your reply
