### ISSUE TITLE
Using Matchformer with my own Images

### ISSUE THREAD

**Issue by dledbetter123** [jamycheung/MatchFormer#9]
Hi I'm looking to use Matchformer and I can't quite figure out how to test the model on my own images, could you include some instructions on how to do so?

**Comment by jamycheung** [comment]
Hi, thanks for your interest. 
Recently, we do not have plan to release the demo code for testing with specific images. I suggest you could check the one provided by LoFTR, for example [this demo](https://github.com/zju3dv/LoFTR#run-loftr-demos). This demo should be applicable for MatchFormer as well.

**Comment by yejiaqing** [comment]
> Hi I'm looking to use Matchformer and I can't quite figure out how to test the model on my own images, could you include some instructions on how to do so?

"Hello, did you successfully modify the code? I am currently facing the same issue. Could you help me?"
